sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t roshin1996/docker-react .


script:
  - docker run -e CI=true roshin1996/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-788598865614"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"